[package]
name = "ruchei-zmq"
version = "0.0.0-0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"
repository = "https://github.com/parrrate/ruchei-zmq"

[dependencies]
async_zmq = "0.4.0"
pin-project = "1.1.6"
